On Premise Connection Configuration
prismatic-io/spectral pull request #176
Opened 2024-02-06 20:52 UTC by robertmaloney

Adds `onPremiseConfig` optional metadata to enable on prem variants of connections. One shortcoming of the currently implementation is that the `replacesInputs` type doesn't have enough type inference to restrict it's array members to the keys of the `inputs` field. An attempt to address that exists on branch `rm/sc-18076/onprem-connections-generics` but it has tradeoffs.

2024-02-13 18:22 UTC, taylorreece requested changes
Thanks @robertmaloney ! Could you please bump `packages/spectral/package.json` version to 8.0.4 and run `yarn` from the base directory to bump the spectral package version?

2024-02-28 21:35 UTC, ryanwersal commented
This has been updated with the reworked on-premise available/controlled implementation we discussed. It also addresses @taylorreece 's request for bumping the version and relocking.

2024-02-28 21:39 UTC, taylorreece approved these changes

2024-02-28 21:44 UTC, robertmaloney commented
Can't formally approve but LGTM

2024-02-28 21:45 UTC, merged